spring:
  application:
    name: news
  data:
    elasticsearch:
      cluster-name: elasticsearch       #es的名称
      cluster-nodes:  10.111.6.2:9300,10.111.6.2:9301,10.111.6.2:9302   # 集群节点服务地址，用逗号分隔
      properties:
        transport:
          tcp:
            connect_timeout:  120s    # 设置连接超时时间

server:
  port: 8080