spring:
  application:
    name: news
  mvc:
      view:
        prefix: /
        suffix: .jsp
  data:
    elasticsearch:
      cluster-name: NewsCluster    # ElasticSearch cluster name , replace with your ES cluster name
      cluster-nodes:  10.80.121.35:9300   # ElasticSearch cluster nodes address , replace with your ES installation address
      properties:
        transport:
          tcp:
            connect_timeout:  120s


server:
  port: 8888